# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/mnt/eyecam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/mnt/eyecam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/mnt/eyecam/CMakeFiles /home/pi/mnt/eyecam/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/mnt/eyecam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eyecam

# Build rule for target.
eyecam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eyecam
.PHONY : eyecam

# fast build rule for target.
eyecam/fast:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/build
.PHONY : eyecam/fast

broadcast.o: broadcast.c.o
.PHONY : broadcast.o

# target to build an object file
broadcast.c.o:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/broadcast.c.o
.PHONY : broadcast.c.o

broadcast.i: broadcast.c.i
.PHONY : broadcast.i

# target to preprocess a source file
broadcast.c.i:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/broadcast.c.i
.PHONY : broadcast.c.i

broadcast.s: broadcast.c.s
.PHONY : broadcast.s

# target to generate assembly for a file
broadcast.c.s:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/broadcast.c.s
.PHONY : broadcast.c.s

camera.o: camera.c.o
.PHONY : camera.o

# target to build an object file
camera.c.o:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/camera.c.o
.PHONY : camera.c.o

camera.i: camera.c.i
.PHONY : camera.i

# target to preprocess a source file
camera.c.i:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/camera.c.i
.PHONY : camera.c.i

camera.s: camera.c.s
.PHONY : camera.s

# target to generate assembly for a file
camera.c.s:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/camera.c.s
.PHONY : camera.c.s

i2c.o: i2c.c.o
.PHONY : i2c.o

# target to build an object file
i2c.c.o:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/i2c.c.o
.PHONY : i2c.c.o

i2c.i: i2c.c.i
.PHONY : i2c.i

# target to preprocess a source file
i2c.c.i:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/i2c.c.i
.PHONY : i2c.c.i

i2c.s: i2c.c.s
.PHONY : i2c.s

# target to generate assembly for a file
i2c.c.s:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/i2c.c.s
.PHONY : i2c.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/main.c.s
.PHONY : main.c.s

motor_ctrl.o: motor_ctrl.c.o
.PHONY : motor_ctrl.o

# target to build an object file
motor_ctrl.c.o:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/motor_ctrl.c.o
.PHONY : motor_ctrl.c.o

motor_ctrl.i: motor_ctrl.c.i
.PHONY : motor_ctrl.i

# target to preprocess a source file
motor_ctrl.c.i:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/motor_ctrl.c.i
.PHONY : motor_ctrl.c.i

motor_ctrl.s: motor_ctrl.c.s
.PHONY : motor_ctrl.s

# target to generate assembly for a file
motor_ctrl.c.s:
	$(MAKE) -f CMakeFiles/eyecam.dir/build.make CMakeFiles/eyecam.dir/motor_ctrl.c.s
.PHONY : motor_ctrl.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... eyecam"
	@echo "... rebuild_cache"
	@echo "... broadcast.o"
	@echo "... broadcast.i"
	@echo "... broadcast.s"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... i2c.o"
	@echo "... i2c.i"
	@echo "... i2c.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... motor_ctrl.o"
	@echo "... motor_ctrl.i"
	@echo "... motor_ctrl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

